// lib/constants/uk_data.dart

const List<String> ukUniversities = [
  'Anglia Ruskin University',
  'Aston University',
  'Bangor University',
  'Bath Spa University',
  'Birkbeck College',
  'Birmingham City University',
  'Bishop Grosseteste University College Lincoln',
  'Bournemouth University',
  'Brunel University',
  'Buckinghamshire New University',
  'Canterbury Christ Church University',
  'Cardiff Metropolitan University',
  'Cardiff University',
  'Central School of Speech and Drama(The)',
  'Courtauld Institute of Art',
  'Coventry University',
  'Cranfield University',
  'De Montfort University',
  'Edge Hill University',
  'Edinburgh Napier University',
  'Glasgow Caledonian University',
  'Glasgow School of Art',
  'Glyndwr University',
  "Goldsmiths' College'",
  'Guildhall School of Music and Drama',
  'Harper Adams University',
  'Heriot-Watt University',
  'Heythrop College',
  'Imperial College of Science, Technology and Medicine',
  'Institute of Cancer Research: Royal Cancer Hospital (The)',
  'Institute of Education, University of London',
  "King's College London",
  'Kingston University',
  'Leeds College of Art',
  'Leeds College of Music',
  'Leeds Metropolitan University',
  'Leeds Trinity University College',
  'Liverpool Hope University',
  'Liverpool John Moores University',
  'London Business School',
  'London Metropolitan University',
  'London School of Economics & Political Science',
  'London School of Hygiene and Tropical Medicine',
  'London South Bank University',
  'Loughborough University',
  'Middlesex University',
  'Newman University College',
  'Northern School of Contemporary Dance',
  'Norwich University College of the Arts',
  'Nottingham Trent University',
  'Open University(The)',
  'Oxford Brookes University',
  'Prifysgol Aberystwyth',
  'Queen Margaret University, Edinburgh',
  'Queen Mary and Westfield College, University of London',
  'Ravensbourne Limited',
  'Roehampton University',
  'Rose Bruford College',
  'Royal Academy of Music',
  'Royal Agricultural College',
  'Royal College of Art(The)',
  'Royal College of Music',
  'Royal Conservatoire of Scotland',
  'Royal Holloway College and Bedford New College',
  'Royal Northern College of Music',
  'Royal Welsh College of Music and Drama Limited',
  'School of Oriental and African Studies',
  'School of Pharmacy University of London(The)',
  'Sheffield Hallam University',
  'Southampton Solent University',
  'Sruc',
  "St George's Hospital Medical School",
  "St Mary's University College",
  "St Mary's University College, Twickenham",
  'Staffordshire University',
  'Stranmillis University College',
  'Swansea Metropolitan University',
  'Swansea University',
  'Teesside University',
  'The Arts University College at Bournemouth',
  'The City University',
  'The Conservatoire for Dance and Drama',
  'The Liverpool Institute for Performing Arts',
  'The Manchester Metropolitan University',
  "The Queen's University of Belfast",
  'The Robert Gordon University',
  'The Royal Veterinary College',
  'The University of Bolton',
  'The University of Buckingham',
  'The University of Chichester',
  'The University of Cumbria',
  'The University of Manchester',
  'The University of Northampton',
  'The University of West London',
  'The University of Westminster',
  'Trinity Laban Conservatoire of Music and Dance Ltd',
  'University Campus Suffolk Ltd',
  'University College Birmingham',
  'University College Falmouth',
  'University College London',
  'University for the Creative Arts',
  'University of Aberdeen',
  'University of Abertay Dundee',
  'University of Bath (The)',
  'University of Bedfordshire',
  'University of Birmingham',
  'University of Bradford',
  'University of Brighton',
  'University of Bristol',
  'University of Cambridge',
  'University of Central Lancashire',
  'University of Chester',
  'University of Derby',
  'University of Dundee',
  'University of Durham',
  'University of East Anglia',
  'University of East London',
  'University of Edinburgh',
  'University of Essex',
  'University of Exeter',
  'University of Glamorgan / Prifysgol Morgannwg',
  'University of Glasgow',
  'University of Gloucestershire',
  'University of Greenwich',
  'University of Hertfordshire',
  'University of Huddersfield',
  'University of Hull',
  'University of Keele',
  'University of Kent',
  'University of Lancaster',
  'University of Leeds',
  'University of Leicester',
  'University of Lincoln',
  'University of Liverpool',
  'University of London',
  'University of Newcastle Upon Tyne',
  'University of Northumbria at Newcastle',
  'University of Nottingham',
  'University of Oxford',
  'University of Plymouth',
  'University of Portsmouth',
  'University of Reading',
  'University of Salford',
  'University of Sheffield',
  'University of Southampton',
  'University of St Andrews',
  'University of St Mark & St John',
  'University of Stirling',
  'University of Strathclyde',
  'University of Sunderland',
  'University of Surrey',
  'University of Sussex',
  'University of Ulster',
  'University of Wales Prifysgol Cymru',
  'University of Wales: Trinity Saint David',
  'University of Warwick',
  'University of Winchester',
  'University of Wolverhampton',
  'University of Worcester',
  'University of York',
  'University of the Arts, London',
  'University of the Highlands and Islands',
  'University of the West of England, Bristol',
  'University of the West of Scotland',
  'Writtle College',
  'York St John University',
];