// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDejUsCnc-vlibSBs4lcOcgyYucGemypSU',
    appId: '1:148834837731:web:f7654b2cc85c06c0b711d6',
    messagingSenderId: '148834837731',
    projectId: 'studentunifyapp',
    authDomain: 'studentunifyapp.firebaseapp.com',
    storageBucket: 'studentunifyapp.firebasestorage.app',
    measurementId: 'G-0BBWY5XBKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGbhGIaYQ_J6Y7QGWhnxyVl5BJpUrivcc',
    appId: '1:148834837731:android:e9bde3d11a199d00b711d6',
    messagingSenderId: '148834837731',
    projectId: 'studentunifyapp',
    storageBucket: 'studentunifyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-NvA6J9wZ5M69wK0W1JJ26t2CdGEimDk',
    appId: '1:148834837731:ios:bf6de6a4946a9cfeb711d6',
    messagingSenderId: '148834837731',
    projectId: 'studentunifyapp',
    storageBucket: 'studentunifyapp.firebasestorage.app',
    iosBundleId: 'com.obinna.studentUnifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-NvA6J9wZ5M69wK0W1JJ26t2CdGEimDk',
    appId: '1:148834837731:ios:bf6de6a4946a9cfeb711d6',
    messagingSenderId: '148834837731',
    projectId: 'studentunifyapp',
    storageBucket: 'studentunifyapp.firebasestorage.app',
    iosBundleId: 'com.obinna.studentUnifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDejUsCnc-vlibSBs4lcOcgyYucGemypSU',
    appId: '1:148834837731:web:d2bcddefa81beedcb711d6',
    messagingSenderId: '148834837731',
    projectId: 'studentunifyapp',
    authDomain: 'studentunifyapp.firebaseapp.com',
    storageBucket: 'studentunifyapp.firebasestorage.app',
    measurementId: 'G-1L0D3D0FDM',
  );
}
